import { Landmark } from "@/types/landmarks";

export const LANDMARK_DEFINITIONS: Record<
  string,
  Omit<Landmark, "position">
> = {
  sella: {
    id: "sella",
    name: "Sella",
    abbreviation: "S",
    description: "Center of the pituitary fossa (sella turcica)",
    category: "skeletal",
    color: "#ff4444",
  },
  nasion: {
    id: "nasion",
    name: "Nasion",
    abbreviation: "N",
    description: "Most anterior point of the frontonasal suture",
    category: "skeletal",
    color: "#ff4444",
  },
  "a-point": {
    id: "a-point",
    name: "A Point (Subspinale)",
    abbreviation: "A",
    description:
      "Deepest midline point on the maxilla between ANS and prosthion",
    category: "skeletal",
    color: "#ff4444",
  },
  "b-point": {
    id: "b-point",
    name: "B Point (Supramentale)",
    abbreviation: "B",
    description:
      "Deepest midline point on the mandible between infradentale and pogonion",
    category: "skeletal",
    color: "#ff4444",
  },
  pogonion: {
    id: "pogonion",
    name: "Pogonion",
    abbreviation: "Pog",
    description: "Most anterior point of the chin on the symphysis",
    category: "skeletal",
    color: "#ff4444",
  },
  menton: {
    id: "menton",
    name: "Menton",
    abbreviation: "Me",
    description: "Lowest point on the mandibular symphysis",
    category: "skeletal",
    color: "#ff4444",
  },
  gnathion: {
    id: "gnathion",
    name: "Gnathion",
    abbreviation: "Gn",
    description: "Most anterior-inferior point on the chin",
    category: "skeletal",
    color: "#ff4444",
  },
  gonion: {
    id: "gonion",
    name: "Gonion",
    abbreviation: "Go",
    description: "Most posterior-inferior point on the angle of the mandible",
    category: "skeletal",
    color: "#ff4444",
  },
  orbitale: {
    id: "orbitale",
    name: "Orbitale",
    abbreviation: "Or",
    description: "Lowest point on the infraorbital rim",
    category: "skeletal",
    color: "#ff4444",
  },
  porion: {
    id: "porion",
    name: "Porion",
    abbreviation: "Po",
    description: "Uppermost point on the external auditory meatus",
    category: "skeletal",
    color: "#ff4444",
  },
  "anterior-nasal-spine": {
    id: "anterior-nasal-spine",
    name: "Anterior Nasal Spine",
    abbreviation: "ANS",
    description: "Tip of the anterior nasal spine",
    category: "skeletal",
    color: "#ff4444",
  },
  "posterior-nasal-spine": {
    id: "posterior-nasal-spine",
    name: "Posterior Nasal Spine",
    abbreviation: "PNS",
    description: "Tip of the posterior nasal spine",
    category: "skeletal",
    color: "#ff4444",
  },
  "upper-incisor-tip": {
    id: "upper-incisor-tip",
    name: "Upper Incisor Tip",
    abbreviation: "U1",
    description: "Incisal edge of the most anterior maxillary incisor",
    category: "dental",
    color: "#44ff44",
  },
  "lower-incisor-tip": {
    id: "lower-incisor-tip",
    name: "Lower Incisor Tip",
    abbreviation: "L1",
    description: "Incisal edge of the most anterior mandibular incisor",
    category: "dental",
    color: "#44ff44",
  },
  "upper-incisor-root": {
    id: "upper-incisor-root",
    name: "Upper Incisor Root Apex",
    abbreviation: "U1R",
    description: "Root apex of the maxillary central incisor",
    category: "dental",
    color: "#44ff44",
  },
  "lower-incisor-root": {
    id: "lower-incisor-root",
    name: "Lower Incisor Root Apex",
    abbreviation: "L1R",
    description: "Root apex of the mandibular central incisor",
    category: "dental",
    color: "#44ff44",
  },
  "upper-first-molar": {
    id: "upper-first-molar",
    name: "Upper First Molar",
    abbreviation: "U6",
    description: "Mesial cusp tip of maxillary first molar",
    category: "dental",
    color: "#44ff44",
  },
  "lower-first-molar": {
    id: "lower-first-molar",
    name: "Lower First Molar",
    abbreviation: "L6",
    description: "Mesial cusp tip of mandibular first molar",
    category: "dental",
    color: "#44ff44",
  },
  "soft-tissue-nasion": {
    id: "soft-tissue-nasion",
    name: "Soft Tissue Nasion",
    abbreviation: "N'",
    description: "Most anterior point of soft tissue overlying nasion",
    category: "soft-tissue",
    color: "#4444ff",
  },
  pronasale: {
    id: "pronasale",
    name: "Pronasale",
    abbreviation: "Prn",
    description: "Most anterior point of the nose",
    category: "soft-tissue",
    color: "#4444ff",
  },
  subnasale: {
    id: "subnasale",
    name: "Subnasale",
    abbreviation: "Sn",
    description: "Junction of nose and upper lip in the midline",
    category: "soft-tissue",
    color: "#4444ff",
  },
  "upper-lip": {
    id: "upper-lip",
    name: "Upper Lip",
    abbreviation: "UL",
    description: "Most anterior point of the upper lip",
    category: "soft-tissue",
    color: "#4444ff",
  },
  "lower-lip": {
    id: "lower-lip",
    name: "Lower Lip",
    abbreviation: "LL",
    description: "Most anterior point of the lower lip",
    category: "soft-tissue",
    color: "#4444ff",
  },
  "soft-tissue-pogonion": {
    id: "soft-tissue-pogonion",
    name: "Soft Tissue Pogonion",
    abbreviation: "Pog'",
    description: "Most anterior point of soft tissue chin",
    category: "soft-tissue",
    color: "#4444ff",
  },
  articulare: {
    id: "articulare",
    name: "Articulare",
    abbreviation: "Ar",
    description:
      "Intersection of posterior border of ramus and inferior border of cranial base",
    category: "skeletal",
    color: "#ff4444",
  },
  basion: {
    id: "basion",
    name: "Basion",
    abbreviation: "Ba",
    description: "Most anterior point on the foramen magnum",
    category: "skeletal",
    color: "#ff4444",
  },
};
